export const materials = [
  {
    label: "Charcoal",
    value: "charcoal",
    class: "rawMaterial",
    src: "/Card-Charcoal.png",
    img: "QmRxLPC7YwHbWp5cMxRoU8JxvfHdwc9Lrv5o5tRu6yRgJx",
  },
  {
    label: "Iron Ore",
    value: "ironore",
    class: "rawMaterial",
    src: "/Card-IronOre.png",
    img: "QmTdUD1TUpkjJQBj6DJmd9XaAJZy76z63rvteanrdhfFXY",
  },
  {
    label: "Iron Sands",
    value: "ironsands",
    class: "rawMaterial",
    src: "/Card-IronSands.png",
    img: "QmPhz8SS2kbWjUzw5imsZqVyxvd4MfoKctTHgsXcJ34u8Z",
  },
  {
    label: "Oak Wood",
    value: "oakwood",
    class: "rawMaterial",
    src: "/Card-Oakwood.png",
    img: "Qmc6wzJAJZXneS1V5eUuir4wfFAbFxTJUZZBeuxZQ92jcW",
  },
  {
    label: "Leather",
    value: "leather",
    class: "rawMaterial",
    src: "/Card-Leather.png",
    img: "QmR8zcgemdKS96adBvkpzKNCfhZ9CfsyDyut7nuvUTo3WS",
  },
  {
    label: "Gemstone",
    value: "gemstones",
    class: "rawMaterial",
    src: "/Card-Gemstone.png",
    img: "QmZt9jpHEawzzJZkQ5gWntL3Fn74JPJLm85Ed7rEYuoM9H",
  },
  {
    label: "Silver Coin",
    value: "silvercoin",
    class: "rawMaterial",
    src: "/Card-Silver.png",
    img: "QmaJJg732YyE6Eqq1vDZAqueKA2eEhpVFTFcNtLGEnni1Y",
  },
  {
    label: "Gold Coin",
    value: "goldcoin",
    class: "rawMaterial",
    src: "/Card-Gold.png",
    img: "QmQrdCZsCQL1mBEEv9ZV9fANCzdicvwTL7TxxVG81mbrMK",
  },
  {
    label: "WOOTZ Steel",
    value: "wootzsteal",
    class: "materialIngot",
    recipe: [4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    src: "/Card-Wootz.png",
    img: "QmeX9fdNmwByvGP7CGMk4j7Ec42z6HLqWTU6a1EHFewvoF",
  },
  {
    label: "TAMAHAGANE Steel",
    value: "tamahaganesteal",
    class: "materialIngot",
    recipe: [4, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0],
    src: "/Card-Tamahagane.png",
    img: "Qmd6kTFezXthNp6ijyZ1tRghfvRtMbEKYZHAvhMKy7mLqV",
  },
  {
    label: "BLOOM Iron",
    value: "bloomiron",
    class: "materialIngot",
    recipe: [2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    src: "/Card-BloomIron.png",
    img: "Qmb2ivgVpr71cMqPAqca8ZihEczcKt2Zk2EqYpznFvMqNJ",
  },
];

export const weapons = [
  {
    label: "Anvil",
    value: "anvil",
    class: "tool",
    recipe: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 6],
    src: "/Card-Anvil.png",
    img: "QmXba3Q2SY7h1EZAvCAKBpbiT5Gk7rQFDVd5r9Moj6k2vb",
  },
  {
    label: "Hammer",
    value: "hammer",
    class: "tool",
    recipe: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 3],
    src: "/Card-Hammer.png",
    img: "QmYbtasEuTb5zWf8iRmjbdGk7xqBP2XULqKvgCLSDdjPuE",
  },
  {
    label: "Tongs",
    value: "tongs",
    class: "tool",
    recipe: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    src: "/Card-Tongs.png",
    img: "QmeR4Di25ZtYzhotXxbok3TohSPDyyoK8GbXsz9YMb8zEg",
  },
  {
    label: "Splitter",
    value: "splitter",
    class: "tool",
    recipe: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 3],
    src: "/Card-Splitter.png",
    img: "QmdFkSEXaTBD3VtfYSsHLXSGLRciKyrYYT219cUJoJm9g1",
  },
  {
    label: "Sword",
    value: "sword",
    class: "uncommonWeapon",
    recipe: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3],
    src: "/Card-Sword.png",
    img: "QmTn8Hb7kaaBQeb9CSj2838AzM6Dz58ZLUaqR6uqXXe1TW",
  },
  {
    label: "Axe",
    value: "axe",
    class: "uncommonWeapon",
    recipe: [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3],
    src: "/Card-Axe.png",
    img: "QmVscVGyLGgqGesUDbQWb1gysTcLgmrLr4uFbXj85TMupT",
  },
  {
    label: "Spear",
    value: "spear",
    class: "uncommonWeapon",
    recipe: [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2],
    src: "/Card-Spear.png",
    img: "QmUCeA7prNed89rGvVhDbibouMVu6FkXJssFAwUwvTYe4N",
  },
  {
    label: "Dagger",
    value: "dagger",
    class: "uncommonWeapon",
    recipe: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2],
    src: "/Card-Dagger.png",
    img: "QmSPkcxZ9mqrSW4AjWhXn2x5iNQsYSYb2mvgLJ3t6PLtSj",
  },
  {
    label: "Crusader Sword",
    value: "crusaderSword",
    class: "rareWeapon",
    recipe: [2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 3],
    src: "/Card-CrusaderSword.png",
    img: "QmW43ZLxGeFahp94k8oaH4M6KAEQ1nNcq3kq2yrjCEAjiS",
  },
  {
    label: "Medieval Sword",
    value: "medievalSword",
    class: "rareWeapon",
    recipe: [2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 3],
    src: "/Card-MedievalSword.png",
    img: "QmPQQpfnEVNB5Bn12BWwSso5vzf3mAmZvC6fYrhi2X6cuy",
  },
  {
    label: "Persian Shamir Sword",
    value: "persianSword",
    class: "epicWeapon",
    recipe: [2, 0, 0, 0, 0, 0, 1, 1, 3, 0, 0],
    src: "/Card-ShamshirSword.png",
    img: "QmQDxRt2sdyAfrXrKvarJEDu1dccbi5opUqCrBfS7j8pjg",
  },
  {
    label: "Persian Jambiya Dagger",
    value: "persianDagger",
    class: "epicWeapon",
    recipe: [2, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0],
    src: "/Card-JambiyaDagger.png",
    img: "QmZmAh4QLkUuF6tcjvKS3fg6vKqKB5XvRR1j5h2oiMHDVq",
  },
  {
    label: "Japanese Katana",
    value: "Katana",
    class: "epicWeapon",
    recipe: [0, 0, 0, 1, 1, 0, 1, 1, 0, 3, 0],
    src: "/Card-Katana.png",
    img: "QmUg3oDYi2GkQ6qfzPs73YmxLPum1fb3pamhmwiKxx7MXp",
  },
  {
    label: "Japanese Wakizashi",
    value: "japaneseWakizashi",
    class: "epicWeapon",
    recipe: [0, 0, 0, 1, 1, 0, 1, 0, 0, 3, 0],
    src: "/Card-wakizashi.png",
    img: "QmTMQyufzTddWpwRgVGMby8JnSSRmiybaQ9qP5g2mVntZB",
  },
  {
    label: "Crystal Jade Sword",
    value: "jadeSword",
    class: "legendaryWeapon",
    recipe: [0, 0, 0, 0, 1, 3, 1, 1, 0, 0, 1],
    src: "/Card-CrystalJade.png",
    img: "QmSoUjx68YCjT4GMKTpkyrttveBZiHY3z3BBCeZkgqXDHv",
  },
  {
    label: "Gemed Snake Sword",
    value: "snakeSword",
    class: "legendaryWeapon",
    recipe: [0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 3],
    src: "/Card-SnakeSword.png",
    img: "QmTy5qWQQm548pESiKVYvDM4uRGhVC3km4nGQLx3882S2N",
  },
];

export const assets = materials.concat(weapons);

export const materialsClasses = [
  { label: "Tools", value: "tools" },
  { label: "Weapons", value: "weapons" },
  { label: "Ingots", value: "ingot" },
  { label: "Raw Material", value: "rawMaterial" },
];

export const weaponsClasses = [
  { label: "Raw options", value: "commonWeapon" },
  { label: "Raw options", value: "uncommonWeapon" },
  { label: "Raw options", value: "rareWeapon" },
  { label: "Raw options", value: "epicWeapon" },
  { label: "Raw options", value: "legendaryWeapon" },
];
